// Executive Dashboard KPI data.
// The `sample` values are ILLUSTRATIVE ONLY -- they demonstrate how the
// dashboard works, not real client data. Say so clearly wherever this is
// displayed. The definitions, formulas, and benchmarks are standard
// industry reference points and don't need personalizing, but feel free
// to adjust benchmarks to match your own point of view as you gain data.

export type Kpi = {
  id: string;
  label: string;
  category: string;
  sample: string;
  trend: "up" | "down" | "flat";
  definition: string;
  formula: string;
  whyItMatters: string;
  howToImprove: string;
  healthy: string;
  warning: string;
  red: string;
  example: string;
};

export const kpis: Kpi[] = [
  {
    id: "customer-health",
    label: "Customer Health Score",
    category: "Health & Sentiment",
    sample: "78/100",
    trend: "up",
    definition: "A composite score combining usage, engagement, support, and sentiment signals into a single account-level health indicator.",
    formula: "Weighted average of adoption %, engagement frequency, support ticket sentiment, and executive engagement -- weights vary by business.",
    whyItMatters: "It's the earliest, most holistic warning system for churn risk -- catches problems before they show up in renewal conversations.",
    howToImprove: "Increase feature adoption, restore executive engagement, and resolve open support issues -- in that priority order for most accounts.",
    healthy: "75-100",
    warning: "50-74",
    red: "Below 50",
    example: "40% adoption + weekly logins + no open tickets + active exec sponsor -> 78/100",
  },
  {
    id: "csat",
    label: "Customer Satisfaction (CSAT)",
    category: "Health & Sentiment",
    sample: "4.4 / 5",
    trend: "flat",
    definition: "A direct measure of satisfaction with a specific interaction or support experience, usually gathered right after that interaction.",
    formula: "(Number of satisfied responses / total responses) x 100",
    whyItMatters: "Tracks the quality of individual touchpoints -- a leading indicator for support and onboarding quality specifically.",
    howToImprove: "Shorten response times, improve first-contact resolution, and follow up on any rating below 4.",
    healthy: "90%+ satisfied",
    warning: "75-89%",
    red: "Below 75%",
    example: "180 satisfied out of 200 responses -> 90% CSAT",
  },
  {
    id: "nps",
    label: "Net Promoter Score (NPS)",
    category: "Health & Sentiment",
    sample: "+42",
    trend: "up",
    definition: "Measures overall customer loyalty by asking how likely a customer is to recommend the product, on a 0-10 scale.",
    formula: "% Promoters (9-10) minus % Detractors (0-6)",
    whyItMatters: "A relationship-level pulse check, not tied to one interaction -- strong leading indicator for expansion and referrals.",
    howToImprove: "Close the loop with detractors individually, and turn passive customers into promoters with proactive value check-ins.",
    healthy: "+30 and above",
    warning: "0 to +29",
    red: "Below 0",
    example: "60% promoters, 18% detractors -> NPS of +42",
  },
  {
    id: "ces",
    label: "Customer Effort Score (CES)",
    category: "Health & Sentiment",
    sample: "5.2 / 7",
    trend: "flat",
    definition: "Measures how much effort a customer had to put in to get an issue resolved or a task done.",
    formula: "Average rating on a 1-7 (or 1-5) effort scale after a support interaction",
    whyItMatters: "Low effort correlates more strongly with loyalty than delight does -- friction is a bigger churn driver than most teams assume.",
    howToImprove: "Remove steps from your support and onboarding flows; resolve issues in fewer touchpoints.",
    healthy: "5.5+",
    warning: "4-5.4",
    red: "Below 4",
    example: "Average of 5.2 across 50 post-ticket surveys",
  },
  {
    id: "grr",
    label: "Gross Revenue Retention (GRR)",
    category: "Revenue",
    sample: "93%",
    trend: "flat",
    definition: "The percentage of recurring revenue retained from existing customers, excluding any expansion revenue -- a pure measure of churn and downgrades.",
    formula: "(Starting ARR - Churn - Downgrades) / Starting ARR x 100",
    whyItMatters: "Shows how well you protect existing revenue, independent of new sales or upsells -- the cleanest churn signal for the business.",
    howToImprove: "Prioritize at-risk account recovery and renewal readiness reviews well before the renewal date.",
    healthy: "90%+",
    warning: "80-89%",
    red: "Below 80%",
    example: "$1M starting ARR, $70K churned -> 93% GRR",
  },
  {
    id: "nrr",
    label: "Net Revenue Retention (NRR)",
    category: "Revenue",
    sample: "112%",
    trend: "up",
    definition: "The percentage of recurring revenue retained and grown from existing customers, including expansion, upsells, and downgrades.",
    formula: "(Starting ARR + Expansion - Churn - Downgrades) / Starting ARR x 100",
    whyItMatters: "The single most-watched SaaS health metric -- above 100% means your existing base is growing revenue on its own.",
    howToImprove: "Identify expansion-ready accounts early and pair Customer Success with Sales on upsell timing.",
    healthy: "105%+",
    warning: "95-104%",
    red: "Below 95%",
    example: "$1M starting ARR, $150K expansion, $30K churn -> 112% NRR",
  },
  {
    id: "arr",
    label: "Annual Recurring Revenue (ARR)",
    category: "Revenue",
    sample: "$2.4M",
    trend: "up",
    definition: "The total value of recurring revenue normalized to a one-year period.",
    formula: "MRR x 12",
    whyItMatters: "The core scoreboard number for the business -- most other metrics exist to explain movement in this one.",
    howToImprove: "Grow through new sales, expansion, and reduced churn -- CS primarily influences the latter two.",
    healthy: "Consistent quarter-over-quarter growth",
    warning: "Flat growth",
    red: "Declining ARR",
    example: "$200K MRR x 12 = $2.4M ARR",
  },
  {
    id: "mrr",
    label: "Monthly Recurring Revenue (MRR)",
    category: "Revenue",
    sample: "$200K",
    trend: "up",
    definition: "The predictable recurring revenue normalized to a monthly period.",
    formula: "Sum of all active subscription revenue for the month",
    whyItMatters: "The most granular, real-time view of revenue health -- movements show up here before they show up in ARR.",
    howToImprove: "Same levers as ARR, tracked monthly instead of annually for faster course correction.",
    healthy: "Steady month-over-month growth",
    warning: "Flat for 2+ months",
    red: "Declining for 2+ months",
    example: "$195K last month, $200K this month -> +2.6% MoM",
  },
  {
    id: "expansion-revenue",
    label: "Expansion Revenue",
    category: "Revenue",
    sample: "$150K",
    trend: "up",
    definition: "Additional recurring revenue from existing customers via upsells, cross-sells, or seat/usage growth.",
    formula: "Sum of upsell + cross-sell + usage-growth revenue from existing accounts",
    whyItMatters: "Expansion is cheaper to win than new-logo revenue and signals genuine product value realization.",
    howToImprove: "Build expansion triggers into health scoring -- flag accounts hitting usage ceilings or asking for more seats.",
    healthy: "20%+ of new ARR from expansion",
    warning: "10-19%",
    red: "Below 10%",
    example: "$150K in upsells against $750K total new ARR -> 20%",
  },
  {
    id: "renewal-rate",
    label: "Renewal Rate",
    category: "Revenue",
    sample: "88%",
    trend: "flat",
    definition: "The percentage of contracts up for renewal in a period that actually renewed.",
    formula: "(Number of accounts renewed / number of accounts up for renewal) x 100",
    whyItMatters: "The most direct measure of whether customers are choosing to stay -- the moment of truth for a CS program.",
    howToImprove: "Start renewal conversations 90+ days out, backed by a documented health review and ROI story.",
    healthy: "90%+",
    warning: "80-89%",
    red: "Below 80%",
    example: "44 of 50 renewals closed -> 88% renewal rate",
  },
  {
    id: "churn-rate",
    label: "Churn Rate",
    category: "Revenue",
    sample: "6%",
    trend: "down",
    definition: "The percentage of customers or revenue lost in a given period.",
    formula: "(Customers lost in period / customers at start of period) x 100",
    whyItMatters: "The inverse of retention -- tracked separately because customer churn and revenue churn can tell different stories.",
    howToImprove: "Build an early warning system from health scores so risk is visible weeks before the cancellation conversation.",
    healthy: "Below 5% annually",
    warning: "5-10%",
    red: "Above 10%",
    example: "6 lost out of 100 customers -> 6% churn",
  },
  {
    id: "product-adoption",
    label: "Product Adoption",
    category: "Adoption",
    sample: "64%",
    trend: "up",
    definition: "The percentage of licensed or available capacity actually being used by an account.",
    formula: "(Active users or usage / licensed users or entitled usage) x 100",
    whyItMatters: "Low adoption is the single strongest predictor of churn -- customers rarely renew what they don't use.",
    howToImprove: "Segment by low-adoption accounts and run targeted re-engagement or training campaigns.",
    healthy: "70%+",
    warning: "40-69%",
    red: "Below 40%",
    example: "320 active seats out of 500 licensed -> 64%",
  },
  {
    id: "feature-adoption",
    label: "Feature Adoption",
    category: "Adoption",
    sample: "3.2 / 6 core features",
    trend: "up",
    definition: "The breadth of a product's core feature set that an account actually uses.",
    formula: "Number of core features used / total core features",
    whyItMatters: "Customers using more of the product see more value and are structurally harder to displace with a competitor.",
    howToImprove: "Build feature-adoption checkpoints into onboarding and QBRs, not just overall login frequency.",
    healthy: "80%+ of core features",
    warning: "40-79%",
    red: "Below 40%",
    example: "3.2 of 6 core features used on average across the account",
  },
  {
    id: "ttv",
    label: "Time-to-Value (TTV)",
    category: "Adoption",
    sample: "18 days",
    trend: "down",
    definition: "The time it takes a new customer to reach their first meaningful, defined value milestone.",
    formula: "Date of first value milestone - date of contract signature",
    whyItMatters: "Faster time-to-value strongly correlates with higher renewal and expansion rates -- first impressions compound.",
    howToImprove: "Define a specific, measurable 'first value' milestone per segment, and build onboarding around hitting it fast.",
    healthy: "Under 30 days (varies by product complexity)",
    warning: "30-60 days",
    red: "Over 60 days",
    example: "Contract signed Jan 1, first key report generated Jan 19 -> 18-day TTV",
  },
  {
    id: "customer-engagement",
    label: "Customer Engagement",
    category: "Adoption",
    sample: "3.1x / week",
    trend: "flat",
    definition: "How frequently and how deeply an account interacts with the product and with your team.",
    formula: "Login frequency + feature usage depth + response rate to outreach, combined into a single view",
    whyItMatters: "Engagement drops are often the first visible sign of risk, well before a formal complaint or cancellation notice.",
    howToImprove: "Set a cadence of proactive touchpoints instead of waiting for the customer to reach out.",
    healthy: "3+ meaningful sessions per week",
    warning: "1-2 per week",
    red: "Less than 1 per week",
    example: "Average of 3.1 active sessions per week over the last month",
  },
  {
    id: "support-volume",
    label: "Support Volume",
    category: "Support",
    sample: "24 tickets / month",
    trend: "flat",
    definition: "The total number of support tickets or requests an account generates in a period.",
    formula: "Count of tickets opened in the period",
    whyItMatters: "Both very high and unusually low volume can be risk signals -- one means friction, the other can mean disengagement.",
    howToImprove: "Pair volume with ticket type -- rising bug reports need a different response than rising how-to questions.",
    healthy: "Stable, in line with account size",
    warning: "Sudden spike or drop of 50%+",
    red: "Sustained spike with no resolution",
    example: "24 tickets this month vs. 22 last month -- stable",
  },
  {
    id: "first-response-time",
    label: "First Response Time",
    category: "Support",
    sample: "2.1 hrs",
    trend: "down",
    definition: "The time between a customer opening a support request and receiving a first human response.",
    formula: "Timestamp of first response - timestamp of ticket creation",
    whyItMatters: "Often the single biggest driver of support satisfaction, independent of how long full resolution takes.",
    howToImprove: "Set tiered SLAs by severity and staff for peak request windows.",
    healthy: "Under 4 hours",
    warning: "4-24 hours",
    red: "Over 24 hours",
    example: "Ticket opened 9:00am, first response 11:06am -> 2.1 hrs",
  },
  {
    id: "time-to-resolution",
    label: "Time to Resolution",
    category: "Support",
    sample: "1.4 days",
    trend: "flat",
    definition: "The total time between a support request being opened and being fully resolved.",
    formula: "Timestamp of resolution - timestamp of ticket creation",
    whyItMatters: "Measures actual problem-solving speed, not just acknowledgment -- a key input into CES and CSAT.",
    howToImprove: "Track resolution time by issue category to find and fix your slowest recurring bottlenecks.",
    healthy: "Under 2 days for standard issues",
    warning: "2-5 days",
    red: "Over 5 days",
    example: "Opened Monday 9am, resolved Tuesday 2:30pm -> 1.4 days",
  },
  {
    id: "exec-sponsor-health",
    label: "Executive Sponsor Health",
    category: "Stakeholder",
    sample: "Engaged",
    trend: "flat",
    definition: "The strength and activity level of the relationship with the account's executive sponsor.",
    formula: "Qualitative rating (Engaged / At Risk / Disengaged) based on meeting cadence and responsiveness",
    whyItMatters: "Losing the executive sponsor is one of the strongest predictors of both churn and stalled expansion.",
    howToImprove: "Maintain a standing executive touchpoint (e.g. quarterly EBR) independent of day-to-day account activity.",
    healthy: "Engaged -- responsive, attends reviews",
    warning: "At Risk -- inconsistent contact",
    red: "Disengaged -- no contact in 90+ days",
    example: "Sponsor attended last 2 QBRs, responds within 48 hours -> Engaged",
  },
  {
    id: "stakeholder-coverage",
    label: "Stakeholder Coverage",
    category: "Stakeholder",
    sample: "4 of 6 mapped",
    trend: "up",
    definition: "How many of the account's key stakeholders (champion, sponsor, technical owner, finance, etc.) you have an active relationship with.",
    formula: "Number of key stakeholder roles with an active relationship / total key roles identified",
    whyItMatters: "Single-threaded accounts (one contact) are highly vulnerable to champion turnover -- coverage is real risk insurance.",
    howToImprove: "Use stakeholder mapping at onboarding and revisit it at every renewal cycle, not just when a contact leaves.",
    healthy: "80%+ of key roles covered",
    warning: "50-79%",
    red: "Below 50%",
    example: "4 of 6 mapped roles (Champion, Sponsor, Tech Owner, Ops) actively engaged",
  },
];
