export type Resource = {
  slug: string;
  title: string;
  category: string;
  readTime: string;
  description: string;
  whatsInside: string[];
  howToUse: string;
};

export const resources: Resource[] = [
  {
    slug: "customer-success-plan-template",
    title: "Customer Success Plan Template",
    category: "Planning",
    readTime: "5 min setup",
    description: "A structured plan that aligns you and the customer on goals, milestones, and ownership from day one -- the single most-referenced document across the customer lifecycle.",
    whatsInside: [
      "Business goals and how success will be measured",
      "Named milestones with dates and owners",
      "Stakeholder register with role and influence",
      "A recurring review cadence, agreed up front",
    ],
    howToUse: "Build this together with the customer in the Discovery stage, not after -- it should reflect their words for what success means, not a generic template filled in on their behalf.",
  },
  {
    slug: "stakeholder-mapping-template",
    title: "Stakeholder Mapping Template",
    category: "Planning",
    readTime: "20 min to complete",
    description: "A visual map of who holds power, who holds influence, and who's actually using the product -- so no account is riding on a single relationship.",
    whatsInside: [
      "Power vs. interest grid for every known contact",
      "Champion, blocker, and neutral classifications",
      "Coverage gaps -- roles you don't have a relationship with yet",
      "A cadence for keeping the map current, not a one-time exercise",
    ],
    howToUse: "Revisit this at onboarding, at renewal, and any time a contact leaves the account -- stakeholder maps go stale fast in real organizations.",
  },
  {
    slug: "onboarding-checklist",
    title: "Onboarding Checklist",
    category: "Onboarding",
    readTime: "3 min reference",
    description: "A pragmatic, stage-by-stage checklist covering technical setup, enablement, and milestone reviews across the full onboarding journey.",
    whatsInside: [
      "Discovery through Value Realization, stage by stage",
      "A defined exit condition for each stage",
      "Who owns each item -- vendor or customer",
    ],
    howToUse: "Use it as a shared document with the customer, not an internal-only tracker -- visibility into progress builds their confidence in the process.",
  },
  {
    slug: "customer-journey-map",
    title: "Customer Journey Map",
    category: "Onboarding",
    readTime: "30 min to build",
    description: "An end-to-end template mapping the path from first contact through advocacy, flagging the moments that make or break the relationship.",
    whatsInside: [
      "Every stage from Awareness through Advocacy",
      "The emotional state and goal at each stage",
      "The CSM action and success signal for each stage",
    ],
    howToUse: "Build one per segment, not one per account -- the goal is a repeatable map for a type of customer, refined with real account data over time.",
  },
  {
    slug: "customer-health-scorecard",
    title: "Customer Health Scorecard",
    category: "Health & Retention",
    readTime: "15 min per account",
    description: "A configurable model that scores account health across five dimensions, with clear thresholds and playbook triggers for each.",
    whatsInside: [
      "The Five Pillars: Adoption, Outcomes, Relationship, Sentiment, Growth Potential",
      "Green / Amber / Red thresholds for each pillar",
      "The playbook to trigger at each risk level",
    ],
    howToUse: "Score every account on the same cadence -- monthly is typical -- so trend, not just a single snapshot, becomes visible over time.",
  },
  {
    slug: "risk-register",
    title: "Risk Register",
    category: "Health & Retention",
    readTime: "10 min per entry",
    description: "A standardized log of active account risks, so every CSM and every leader speaks the same language when escalating a concern.",
    whatsInside: [
      "Risk category, description, probability, and impact",
      "Named owner and target resolution date",
      "Escalation level and current status",
    ],
    howToUse: "Log a risk the moment it's identified, not after it's already become a crisis -- the register is only useful if it's current.",
  },
  {
    slug: "renewal-readiness-checklist",
    title: "Renewal Readiness Checklist",
    category: "Health & Retention",
    readTime: "10 min per account",
    description: "A pre-renewal checklist run well before the renewal window opens, so nothing about the conversation is a surprise.",
    whatsInside: [
      "The six readiness questions from the Renewal Readiness framework",
      "A red-flag list of common late-stage renewal risks",
      "A suggested timeline: 120 / 90 / 60 / 30 days out",
    ],
    howToUse: "Run this at 120 days before renewal, not 30 -- a readiness gap found with 90 days of runway is fixable; the same gap found with 2 weeks left usually isn't.",
  },
  {
    slug: "executive-business-review-deck",
    title: "Executive Business Review Deck",
    category: "Retention & Growth",
    readTime: "1-2 hrs to build",
    description: "An outcome-first EBR structure built for executive audiences -- anchored in business impact, not a feature walkthrough.",
    whatsInside: [
      "The five-question EBR structure",
      "Slide-by-slide outline: Agenda, Goals Recap, Current Performance, Challenges & Actions, Forward Plan, Next Steps",
      "Guidance on having the customer co-present, not just attend",
    ],
    howToUse: "Send the deck for review before the meeting, and where possible, have the customer's own champion present a slide -- it reads as far more credible to their leadership than a vendor presenting alone.",
  },
  {
    slug: "business-case-template",
    title: "Expansion Business Case Template",
    category: "Retention & Growth",
    readTime: "45 min to build",
    description: "An ROI-first framing for an upsell or expansion recommendation, built for an executive audience whose first question is always \"what does this get us.\"",
    whatsInside: [
      "Current-state usage and outcome summary",
      "The specific business need driving the recommendation",
      "ROI calculation and a realistic payback timeline",
    ],
    howToUse: "Never lead with the feature. Lead with the business need it solves, backed by the customer's own usage data.",
  },
  {
    slug: "expansion-conversation-guide",
    title: "Expansion Conversation Guide",
    category: "Retention & Growth",
    readTime: "5 min reference",
    description: "A conversational framework for raising an expansion opportunity so it feels like solving the customer's next problem, not a sales pitch.",
    whatsInside: [
      "Opening framing that starts from the customer's goal, not the product",
      "Questions that surface the real business need before any recommendation",
      "Guidance for coordinating timing with Sales",
    ],
    howToUse: "Use this after the Expansion Opportunity Assessment confirms the account is genuinely ready -- not as a script to force an early conversation.",
  },
  {
    slug: "ai-prompt-library",
    title: "AI Prompt Library for CSMs",
    category: "Operations",
    readTime: "Ongoing reference",
    description: "A working set of prompts for the AI tools most CSMs already have access to -- built to produce a solid first draft, not a finished output.",
    whatsInside: [
      "Account summary and health-narrative prompts",
      "QBR / EBR draft-narrative prompts",
      "Risk-signal analysis and renewal-readiness prompts",
    ],
    howToUse: "Treat every output as a first draft. The judgment on what's actually true about the account still has to come from the CSM who knows it.",
  },
  {
    slug: "success-metrics-dashboard",
    title: "Success Metrics Reference Dashboard",
    category: "Operations",
    readTime: "Ongoing reference",
    description: "A reference set of the metrics that matter most for CS leadership -- health distribution, NRR, renewal rate, adoption, and forecast confidence -- in one view.",
    whatsInside: [
      "The core metric set and how each is calculated",
      "Suggested healthy / warning / red thresholds",
      "Guidance on cadence -- what to review weekly vs. quarterly",
    ],
    howToUse: "Use this as the shared source of truth in leadership reviews, so every conversation starts from the same numbers.",
  },
  {
    slug: "csm-account-handover-checklist",
    title: "CSM Account Handover Checklist",
    category: "Operations",
    readTime: "15 min to complete",
    description: "An urgency-ordered handover checklist so an account transitioning between CSMs never loses context -- built after seeing what happens when it isn't used.",
    whatsInside: [
      "Immediate (Day 1), High (Days 1-2), Standard (Days 3-5), and Ongoing (Week 2) action tiers",
      "Clear ownership split -- outgoing CSM vs. incoming CSM",
      "A rule that handovers are filed and complete before the outgoing CSM's last working day",
    ],
    howToUse: "Treat incomplete handovers as an account risk in their own right, not an administrative afterthought -- gaps here are exactly how accounts go 18 months without a single QBR.",
  },
  {
    slug: "glossary",
    title: "Customer Success Glossary of Terms, Metrics & KPIs",
    category: "Reference Guide",
    readTime: "Ongoing reference",
    description: "A comprehensive A-Z reference covering CS terminology, financial metrics, adoption metrics, health metrics, and a full formula cheat sheet.",
    whatsInside: [
      "Customer Success terminology, A through Z",
      "Financial, adoption, health, experience, renewal, and expansion metrics",
      "A formula cheat sheet and dashboard reference guide",
    ],
    howToUse: "Keep this open during your first few months in any CS role -- it's built to be searched, not read cover to cover.",
  },
  {
    slug: "acronyms-reference",
    title: "Customer Success Acronyms Reference",
    category: "Reference Guide",
    readTime: "Quick reference",
    description: "The shorthand -- NRR, GRR, TTV, QBR, PQL, and dozens more -- decoded in one place.",
    whatsInside: ["Every common CS and SaaS acronym", "Plain-language expansions, not just the letters"],
    howToUse: "The fastest way to get up to speed in a meeting full of acronyms you haven't met yet.",
  },
  {
    slug: "career-roadmap",
    title: "Customer Success Career Roadmap",
    category: "Reference Guide",
    readTime: "10 min read",
    description: "A path from first CS role through to leadership, with the skills and signals that mark each stage.",
    whatsInside: ["Stage-by-stage career progression", "Skills to build at each level", "Signals you're ready for the next stage"],
    howToUse: "Revisit this every 6-12 months to check whether your role is still stretching you.",
  },
  {
    slug: "interview-prep",
    title: "Customer Success Interview Questions & Model Answers",
    category: "Reference Guide",
    readTime: "20 min read",
    description: "Common CSM interview questions paired with model answer structures, not scripts to memorize.",
    whatsInside: ["Behavioral and scenario-based questions", "Model answer frameworks", "What interviewers are actually listening for"],
    howToUse: "Practice structuring your own real examples into these frameworks rather than memorizing the sample answers verbatim.",
  },
  {
    slug: "tools-and-tech-stack",
    title: "Customer Success Tools & Technology Stack",
    category: "Reference Guide",
    readTime: "12 min read",
    description: "The platforms that make up a modern CS operation -- CRM, health scoring, communication, and analytics tools.",
    whatsInside: ["Category-by-category tool breakdown", "What each type of tool is actually for"],
    howToUse: "Useful both for evaluating your own stack and for speaking knowledgeably about tooling in an interview.",
  },
  {
    slug: "cs-playbooks",
    title: "Customer Success Playbooks",
    category: "Reference Guide",
    readTime: "15 min read",
    description: "Repeatable response plans for the account situations that come up again and again.",
    whatsInside: ["Named playbooks for common risk and opportunity scenarios", "Step-by-step response sequences"],
    howToUse: "Adapt these as starting points for your own team's playbooks rather than following them word for word.",
  },
  {
    slug: "templates-library",
    title: "Customer Success Templates Library",
    category: "Reference Guide",
    readTime: "10 min read",
    description: "A reference index across the full template set in this library, with guidance on when to reach for each one.",
    whatsInside: ["A map of every template in this Resource Library", "Guidance on which template fits which moment in the lifecycle"],
    howToUse: "Start here if you're not sure which specific resource you need for a given situation.",
  },
  {
    slug: "100-metrics",
    title: "100 Customer Success Metrics Every Professional Should Know",
    category: "Reference Guide",
    readTime: "Ongoing reference",
    description: "A wide-angle companion to the core Glossary -- a broader sweep of metrics across the entire CS and SaaS landscape.",
    whatsInside: ["100 metrics spanning CS, product, and revenue", "Organized for quick scanning, not memorization"],
    howToUse: "Use alongside the Glossary when you need a metric that's more specialized or product-specific.",
  },
  {
    slug: "strategic-frameworks-reference",
    title: "Customer Success Frameworks & Strategic Models",
    category: "Reference Guide",
    readTime: "12 min read",
    description: "A reference companion to the Framework Library -- quick-scan summaries of each model in one document.",
    whatsInside: ["A condensed summary of every framework in the Framework Library", "Built for quick lookup, not a substitute for the full framework pages"],
    howToUse: "Keep this as a quick-reference alongside the full Framework Library pages on this site.",
  },
  {
    slug: "career-toolkit",
    title: "Customer Success Career Toolkit",
    category: "Reference Guide",
    readTime: "15 min read",
    description: "Practical tools for building and advancing a CS career -- rounding out the roadmap and interview prep guides.",
    whatsInside: ["Self-assessment tools", "Career planning worksheets", "Practical next-step guidance"],
    howToUse: "Pair with the Career Roadmap resource for a fuller picture of where you are and what's next.",
  },
];

export function getResource(slug: string) {
  return resources.find((r) => r.slug === slug);
}
